g++.exe -Wall -std=c++11 -Winvalid-pch -include "src\core\stdafx.h" -Wno-comment -O2 -Wno-strict-aliasing -DNDEBUG -std=c++11 -iquoteobj\Release\src\core -Iobj\Release\src\core -I.  -c "src\core\stdafx.h" -o obj\Release\src\core\stdafx.h.gch
g++.exe -Wall -std=c++11 -Winvalid-pch -include "src\core\stdafx.h" -Wno-comment -O2 -Wno-strict-aliasing -DNDEBUG -std=c++11 -iquoteobj\Release\src\core -Iobj\Release\src\core -I.  -c "src\billboard.cpp" -o obj\Release\src\billboard.o
g++.exe -Wall -std=c++11 -Winvalid-pch -include "src\core\stdafx.h" -Wno-comment -O2 -Wno-strict-aliasing -DNDEBUG -std=c++11 -iquoteobj\Release\src\core -Iobj\Release\src\core -I.  -c "src\celestial_body_generator.cpp" -o obj\Release\src\celestial_body_generator.o
g++.exe -Wall -std=c++11 -Winvalid-pch -include "src\core\stdafx.h" -Wno-comment -O2 -Wno-strict-aliasing -DNDEBUG -std=c++11 -iquoteobj\Release\src\core -Iobj\Release\src\core -I.  -c "src\core\exception.cpp" -o obj\Release\src\core\exception.o
g++.exe -Wall -std=c++11 -Winvalid-pch -include "src\core\stdafx.h" -Wno-comment -O2 -Wno-strict-aliasing -DNDEBUG -std=c++11 -iquoteobj\Release\src\core -Iobj\Release\src\core -I.  -c "src\core\file_reader.cpp" -o obj\Release\src\core\file_reader.o
g++.exe -Wall -std=c++11 -Winvalid-pch -include "src\core\stdafx.h" -Wno-comment -O2 -Wno-strict-aliasing -DNDEBUG -std=c++11 -iquoteobj\Release\src\core -Iobj\Release\src\core -I.  -c "src\core\gltexture.cpp" -o obj\Release\src\core\gltexture.o
g++.exe -Wall -std=c++11 -Winvalid-pch -include "src\core\stdafx.h" -Wno-comment -O2 -Wno-strict-aliasing -DNDEBUG -std=c++11 -iquoteobj\Release\src\core -Iobj\Release\src\core -I.  -c "src\core\jpeg_image.cpp" -o obj\Release\src\core\jpeg_image.o
g++.exe -Wall -std=c++11 -Winvalid-pch -include "src\core\stdafx.h" -Wno-comment -O2 -Wno-strict-aliasing -DNDEBUG -std=c++11 -iquoteobj\Release\src\core -Iobj\Release\src\core -I.  -c "src\core\png_image.cpp" -o obj\Release\src\core\png_image.o
g++.exe -Wall -std=c++11 -Winvalid-pch -include "src\core\stdafx.h" -Wno-comment -O2 -Wno-strict-aliasing -DNDEBUG -std=c++11 -iquoteobj\Release\src\core -Iobj\Release\src\core -I.  -c "src\core\window.cpp" -o obj\Release\src\core\window.o
g++.exe -Wall -std=c++11 -Winvalid-pch -include "src\core\stdafx.h" -Wno-comment -O2 -Wno-strict-aliasing -DNDEBUG -std=c++11 -iquoteobj\Release\src\core -Iobj\Release\src\core -I.  -c "src\free_roam_camera.cpp" -o obj\Release\src\free_roam_camera.o
g++.exe -Wall -std=c++11 -Winvalid-pch -include "src\core\stdafx.h" -Wno-comment -O2 -Wno-strict-aliasing -DNDEBUG -std=c++11 -iquoteobj\Release\src\core -Iobj\Release\src\core -I.  -c "src\light.cpp" -o obj\Release\src\light.o
g++.exe -Wall -std=c++11 -Winvalid-pch -include "src\core\stdafx.h" -Wno-comment -O2 -Wno-strict-aliasing -DNDEBUG -std=c++11 -iquoteobj\Release\src\core -Iobj\Release\src\core -I.  -c "src\main.cpp" -o obj\Release\src\main.o
g++.exe -Wall -std=c++11 -Winvalid-pch -include "src\core\stdafx.h" -Wno-comment -O2 -Wno-strict-aliasing -DNDEBUG -std=c++11 -iquoteobj\Release\src\core -Iobj\Release\src\core -I.  -c "src\main_form.cpp" -o obj\Release\src\main_form.o
g++.exe -Wall -std=c++11 -Winvalid-pch -include "src\core\stdafx.h" -Wno-comment -O2 -Wno-strict-aliasing -DNDEBUG -std=c++11 -iquoteobj\Release\src\core -Iobj\Release\src\core -I.  -c "src\orthogonal_camera.cpp" -o obj\Release\src\orthogonal_camera.o
g++.exe -Wall -std=c++11 -Winvalid-pch -include "src\core\stdafx.h" -Wno-comment -O2 -Wno-strict-aliasing -DNDEBUG -std=c++11 -iquoteobj\Release\src\core -Iobj\Release\src\core -I.  -c "src\skybox.cpp" -o obj\Release\src\skybox.o
g++.exe -Wall -std=c++11 -Winvalid-pch -include "src\core\stdafx.h" -Wno-comment -O2 -Wno-strict-aliasing -DNDEBUG -std=c++11 -iquoteobj\Release\src\core -Iobj\Release\src\core -I.  -c "src\solar_system_body.cpp" -o obj\Release\src\solar_system_body.o
g++.exe -Wall -std=c++11 -Winvalid-pch -include "src\core\stdafx.h" -Wno-comment -O2 -Wno-strict-aliasing -DNDEBUG -std=c++11 -iquoteobj\Release\src\core -Iobj\Release\src\core -I.  -c "src\tracking_camera.cpp" -o obj\Release\src\tracking_camera.o
g++.exe -Llib -o bin\Release\SolarSystem.exe obj\Release\src\billboard.o obj\Release\src\celestial_body_generator.o obj\Release\src\core\exception.o obj\Release\src\core\file_reader.o obj\Release\src\core\gltexture.o obj\Release\src\core\jpeg_image.o obj\Release\src\core\png_image.o obj\Release\src\core\window.o obj\Release\src\free_roam_camera.o obj\Release\src\light.o obj\Release\src\main.o obj\Release\src\main_form.o obj\Release\src\orthogonal_camera.o obj\Release\src\skybox.o obj\Release\src\solar_system_body.o obj\Release\src\tracking_camera.o  -static-libgcc -static-libstdc++ -lopengl32 -lglu32 -s  lib\libglew32.dll.a lib\glfw3dll.a lib\libjpeg.dll.a lib\libturbojpeg.dll.a lib\libpng.a lib\libz.dll.a -mwindows
pause